using Leaf.Plugins.Storyboard;
using Leaf.Sdk;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json.Nodes;
using Xunit;
namespace Storyboard.Testing;
public sealed class PortalTests {
 private static async Task Error(string code,Func<Task> action){Assert.Equal(code,(await Assert.ThrowsAsync<StoryException>(action)).Code);}
 [Fact] public async Task TypedManagementPortalRegistrationMasksKeyAndRejectsStaleOrMalformedReplacement(){await using var f=await Fixture.Create();await f.Admin.FenceAsync(true,f.Owner,default);var secret=StoryJson.Token();var fields=new JsonObject{["key"]="admin-portal",["campaign"]=f.Campaign.Id.ToString(),["google_client_id"]="fixture-client",["portal_secret"]=secret,["legacy_workspace"]="fixture-workspace"};foreach(var field in Fixture.Schema())fields[field.Key]=field.Value?.DeepClone();var request=new JsonObject{["name"]="Fixture registration",["data"]=fields,["expectedUpdatedAt"]=null};var saved=StoryJson.Object(await f.Admin.PutAsync("storyboard-portal","admin-portal",request,f.Owner,default));Assert.True(saved.Flag("portalSecretConfigured"));Assert.DoesNotContain(secret,saved.ToJsonString());Assert.Equal(f.Owner,saved["data"]!.AsObject().Text("owner_id"));await Error("write_conflict",()=>f.Admin.PutAsync("storyboard-portal","admin-portal",request,f.Owner,default));request["expectedUpdatedAt"]=saved.Text("updatedAt");fields["google_client_id"]=42;await Error("invalid_json",()=>f.Admin.PutAsync("storyboard-portal","admin-portal",request,f.Owner,default));}
 [Fact] public async Task IdentityCannotEnrollAnExistingForeignAccountAndNewEnrollmentRecoversAfterInterruption(){await using var f=await Fixture.Create();var p=await f.Portal();f.Google.Subject="fixture:outsider";var input=new JsonObject{["idToken"]="fixture-token",["nonce"]="fixture-nonce"};await Error("campaign_access_denied",()=>f.Portals.IdentityAsync(p,input));f.Google.Subject="fixture:new-enrollment";var fail=true;f.Entities.BeforeCas=(type,slug,data)=>{if(type=="storyboard-player"&&fail){fail=false;throw new IOException("fixture interrupted enrollment");}};await Assert.ThrowsAsync<IOException>(()=>f.Portals.IdentityAsync(p,input));f.Entities.BeforeCas=null;var identity=StoryJson.Object(await f.Portals.IdentityAsync(p,input));Assert.Equal("player",identity.Text("role"));Assert.Single(await f.Store.AllAsync("storyboard-player",new Dictionary<string,object?>{["account"]=identity.Text("accountId")}));}
 [Theory][InlineData("null")][InlineData("[]")][InlineData("{\"idToken\":42,\"nonce\":\"x\"}")][InlineData("{")]
 public async Task PortalMalformedInputsAre400AndFenceIs503(string json){await using var f=await Fixture.Create();var p=await f.Portal();using var client=await f.Host();client.DefaultRequestHeaders.Add("X-Test-Leaf-User",f.Owner);client.DefaultRequestHeaders.Add("X-Storyboard-Portal-Key",p.Data.Text("portal_secret"));var malformed=await client.PostAsync("/api/apps/storyboard/portals/fixture/identity",new StringContent(json,System.Text.Encoding.UTF8,"application/json"));Assert.Equal(HttpStatusCode.BadRequest,malformed.StatusCode);await f.Admin.FenceAsync(true,f.Owner,default);var fenced=await client.PostAsJsonAsync("/api/apps/storyboard/portals/fixture/identity",new{idToken="fixture-token",nonce="fixture-nonce"});Assert.Equal(HttpStatusCode.ServiceUnavailable,fenced.StatusCode);}
 [Fact] public async Task RegistrationRequiresLeafAuthAndExactServerKeyWithoutSecretEcho(){await using var f=await Fixture.Create();var portal=await f.Portal();using var client=await f.Host();foreach(var (user,key,status) in new[]{("",portal.Data.Text("portal_secret"),401),(f.Owner,"",403),(f.Owner,StoryJson.Token(),403),(f.Owner,portal.Data.Text("portal_secret"),200)}){using var request=new HttpRequestMessage(HttpMethod.Get,"/api/apps/storyboard/portals/fixture/characters");if(user!="")request.Headers.Add("X-Test-Leaf-User",user);if(key!="")request.Headers.Add("X-Storyboard-Portal-Key",key);request.Headers.Add("X-Storyboard-Owner",f.Player.Id.ToString());var response=await client.SendAsync(request);Assert.Equal(status,(int)response.StatusCode);Assert.DoesNotContain(portal.Data.Text("portal_secret"),await response.Content.ReadAsStringAsync());}}
 [Fact] public async Task IdentityKeepsCurrentRoleAndDoesNotReactivateRemovedMember(){await using var f=await Fixture.Create();var p=await f.Portal();f.Google.Subject="fixture:player";var input=new JsonObject{["idToken"]="fixture-token",["nonce"]="fixture-nonce"};Assert.Equal("player",StoryJson.Object(await f.Portals.IdentityAsync(p,input)).Text("role"));var m=await f.Campaigns.MembershipAsync(f.Campaign.Id.ToString(),f.Player.Id.ToString());await f.Campaigns.RemoveMemberAsync(f.Campaign.Id.ToString(),f.Gm.Id.ToString(),m.Id.ToString());await Error("campaign_access_denied",()=>f.Portals.IdentityAsync(p,input));Assert.False((await f.Entities.GetAsync(m.Id))!.Data.Flag("active"));}
 [Fact] public async Task NewIdentityOnlyAutoJoinsConfiguredCampaignAsPlayerAndRejectsBadNonce(){await using var f=await Fixture.Create();var p=await f.Portal();var input=new JsonObject{["idToken"]="fixture-token",["nonce"]="wrong"};await Error("google_sign_in_failed",()=>f.Portals.IdentityAsync(p,input));Assert.Null(await f.Entities.GetBySlugAsync("storyboard-account",StoryAccess.AccountSlug(f.Google.Subject)));input["nonce"]="fixture-nonce";var identity=StoryJson.Object(await f.Portals.IdentityAsync(p,input));Assert.Equal("player",identity.Text("role"));var id=identity.Text("accountId");Assert.Single(await f.Store.AllAsync("storyboard-player",new Dictionary<string,object?>{["account"]=id}));}
 [Fact] public async Task LegacyOwnerIsExactCompatibilityIdentityAndAliasIsActorScoped(){await using var f=await Fixture.Create();var legacy=Guid.NewGuid().ToString();await f.Entities.PatchAsync(f.Player.Id,new(){["legacy_owner"]=legacy});var p=await f.Portal();f.Google.Subject="fixture:player";var response=StoryJson.Object(await f.Portals.IdentityAsync(p,new(){["idToken"]="fixture-token",["nonce"]="fixture-nonce"}));Assert.Equal(legacy,response.Text("ownerId"));Assert.Equal(f.Player.Id.ToString(),response.Text("accountId"));var oldChar=Guid.NewGuid().ToString();var character=await f.Character(await f.Entities.GetAsync(f.Player.Id)??throw new Exception(),oldChar);var projected=StoryJson.Object(await f.Portals.GetAsync(p,legacy,oldChar));Assert.Equal(character.Id.ToString(),projected.Text("id"));var data=projected["data"]!.AsObject();Assert.Equal(legacy,data.Text("account"));Assert.Equal("fixture-workspace",data.Text("parent"));Assert.False(data.ContainsKey("source_extra"));Assert.Equal("preserved",character.Data["game_data"]!.AsObject().Text("source_extra"));Assert.Equal(character.Data["game_data"]!["portrait"]!.GetValue<string>(),data.Text("portrait"));await Error("not_found",()=>f.Portals.GetAsync(p,f.Gm.Id.ToString(),oldChar));Assert.Equal(character.Id,StoryJson.Id(StoryJson.Object(await f.Portals.GetAsync(p,f.Player.Id.ToString(),character.Id.ToString())).Text("id")));}
 [Fact] public async Task CrossCampaignDisabledAndRemovedOwnersAreDenied(){await using var f=await Fixture.Create();var p=await f.Portal();await Error("campaign_access_denied",()=>f.Portals.ListAsync(p,f.Outsider.Id.ToString()));await f.Entities.PatchAsync(f.Player.Id,new(){["enabled"]=false});await Error("account_disabled",()=>f.Portals.ListAsync(p,f.Player.Id.ToString()));await f.Entities.PatchAsync(f.Player.Id,new(){["enabled"]=true});var second=await f.Campaigns.CreateAsync(f.Gm.Id.ToString(),new("Second fixture",Guid.NewGuid().ToString()));var other=await f.Portal("other",second.Id.ToString());await Error("campaign_access_denied",()=>f.Portals.ListAsync(other,f.Player.Id.ToString()));}
 [Theory][InlineData("account")][InlineData("parent")][InlineData("campaign")][InlineData("player")][InlineData("installation")][InlineData("portal_secret")]
 public async Task MaliciousOwnershipPatchIsDeniedAndExistingFieldsRemain(string key){await using var f=await Fixture.Create();var p=await f.Portal();var character=await f.Character(f.Player);await Error("character_field_forbidden",()=>f.Portals.WriteAsync(p,f.Player.Id.ToString(),character.Id.ToString(),new(){["data"]=new JsonObject{[key]="attacker"}}));Assert.Equal("preserved",(await f.Entities.GetAsync(character.Id))!.Data["game_data"]!.AsObject().Text("source_extra"));}
 [Fact] public async Task TypedPatchPreservesSourceKeysAndRetryCreationDoesNotDuplicate(){await using var f=await Fixture.Create();var p=await f.Portal();var input=new JsonObject{["name"]="New fixture character",["data"]=new JsonObject{["gid"]="FIX_002",["age"]="28",["tier"]=2,["onboarded"]=false}};var one=StoryJson.Object(await f.Portals.WriteAsync(p,f.Player.Id.ToString(),null,input));var two=StoryJson.Object(await f.Portals.WriteAsync(p,f.Player.Id.ToString(),null,input));Assert.Equal(one.Text("id"),two.Text("id"));await f.Portals.WriteAsync(p,f.Player.Id.ToString(),one.Text("id"),new(){["data"]=new JsonObject{["statement"]="Fixture statement"}});var after=StoryJson.Object(await f.Portals.GetAsync(p,f.Player.Id.ToString(),one.Text("id")))["data"]!.AsObject();Assert.Equal("28",after.Text("age"));Assert.Equal("FIX_002",after.Text("gid"));Assert.False(after.Flag("onboarded"));}
 [Fact] public async Task PortraitRequiresSameLegacyOwnerOrSharedAndCorrectWorkspace(){await using var f=await Fixture.Create();var p=await f.Portal();var ch=await f.Character(f.Player);var portrait=await f.Entities.CreateAsync("fixture-portrait","Fixture portrait",new(){["account"]=f.Gm.Id.ToString(),["parent"]="fixture-workspace",["image_url"]="/api/assets/"+Guid.NewGuid()+".webp"});JsonObject Input()=>new(){["data"]=new JsonObject{["portrait"]=portrait.Id.ToString()}};await Error("portrait_access_denied",()=>f.Portals.WriteAsync(p,f.Player.Id.ToString(),ch.Id.ToString(),Input()));await f.Entities.PatchAsync(portrait.Id,new(){["account"]="",["parent"]="other-workspace"});await Error("portrait_access_denied",()=>f.Portals.WriteAsync(p,f.Player.Id.ToString(),ch.Id.ToString(),Input()));await f.Entities.PatchAsync(portrait.Id,new(){["parent"]="fixture-workspace"});await f.Portals.WriteAsync(p,f.Player.Id.ToString(),ch.Id.ToString(),Input());Assert.EndsWith(".webp",(await f.Entities.GetAsync(ch.Id))!.Data.Text("portrait"));}
 [Fact] public async Task FenceBlocksPortalAndCampaignWritesButOwnerFenceControlIsAudited(){await using var f=await Fixture.Create();var p=await f.Portal();await f.Admin.FenceAsync(true,f.Owner,default);await Error("writes_fenced",()=>f.Portals.IdentityAsync(p,new(){["idToken"]="fixture-token",["nonce"]="fixture-nonce"}));await Error("writes_fenced",()=>f.Portals.WriteAsync(p,f.Player.Id.ToString(),null,new(){["name"]="Fixture",["data"]=new JsonObject{["gid"]="FIX_003"}}));await Error("writes_fenced",()=>f.Campaigns.ArchiveAsync(f.Campaign.Id.ToString(),f.Gm.Id.ToString(),true));Assert.Contains(await f.Store.AuditListAsync(),r=>r.Data.Text("action")=="settings.fence");}
 [Fact] public async Task ManagementRejectsStaleCasUnfencedWritesAndUnrelatedLeafUser(){await using var f=await Fixture.Create();using var client=await f.Host();using var denied=new HttpRequestMessage(HttpMethod.Put,"/api/apps/storyboard/manage/fence"){Content=JsonContent.Create(new{writesFenced=true})};denied.Headers.Add("X-Test-Leaf-User",f.Outsider.Id.ToString());Assert.Equal(HttpStatusCode.Forbidden,(await client.SendAsync(denied)).StatusCode);await Error("management_writes_require_fence",()=>f.Admin.PutAsync("storyboard-account",f.Player.Slug,new(){["name"]="Fixture",["data"]=new JsonObject(),["expectedUpdatedAt"]=null},f.Owner,default));await f.Admin.FenceAsync(true,f.Owner,default);await Error("write_conflict",()=>f.Admin.PutAsync("storyboard-account",f.Player.Slug,new(){["name"]="Fixture",["data"]=new JsonObject(),["expectedUpdatedAt"]=null},f.Owner,default));}
 [Fact] public async Task OwnerCanResolveProtectedRoleIdsForFencedMigration(){await using var f=await Fixture.Create();using var client=await f.Host();using var request=new HttpRequestMessage(HttpMethod.Get,"/api/apps/storyboard/manage/roles");request.Headers.Add("X-Test-Leaf-User",f.Owner);var response=await client.SendAsync(request);Assert.Equal(HttpStatusCode.OK,response.StatusCode);var body=await response.Content.ReadAsStringAsync();var roles=JsonNode.Parse(body)!.AsArray();Assert.Contains(roles,r=>r!["key"]!.GetValue<string>()=="gm");Assert.Contains(roles,r=>r!["key"]!.GetValue<string>()=="player");Assert.DoesNotContain("owner_id",body);}
}
