using Leaf.Sdk;
using Leaf.Sdk.Services;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;

namespace Leaf.Plugins.Storyboard;

public sealed class StoryTranscript(StoryStore store,StoryCampaigns campaigns,IComputeJobs compute,IAssets assets,TimeProvider clock,ILogger<StoryTranscript> logger):BackgroundService {
 const string Stream="transcript";
 static readonly HashSet<string> EventKinds=["speech","action","intent","rationale","tool","system","note","correction"];
 static readonly HashSet<string> Channels=["roleplay","irl","meta"];
 static readonly HashSet<string> ActorTypes=["player","character","gm","npc","agent","system","table"];
 static object SessionProjection(LeafEntity s)=>new{id=s.Id,name=s.Name,state=s.Data.Text("state"),startedAt=s.Data.Text("started_at"),endedAt=s.Data.Text("ended_at")==""?null:s.Data.Text("ended_at"),startedBy=s.Data.Text("started_by"),roleplayAnchor=s.Data.Text("roleplay_anchor"),roleplayAnchorAt=s.Data.Text("roleplay_anchor_at")};
 async Task<LeafEntity> RequireSessionAsync(string campaign,string session,string actor,bool gm,CancellationToken ct){await campaigns.MembershipAsync(campaign,actor,gm,ct);var value=await store.RequireAsync("storyboard-campaign-session",session,ct);if(value.Data.Text("campaign")!=campaign)throw new StoryException("not_found",404);return value;}
 static string Iso(DateTimeOffset value)=>value.ToUniversalTime().ToString("O");
 static string SessionSlug(string campaign,string operation)=>"play-"+StoryJson.Hash(campaign+":"+operation);
 static string JobSlug(string session,string operation)=>"transcript-"+StoryJson.Hash(session+":"+operation);
 static JsonObject Actor(TranscriptActorWrite? value){value??=new("table","Table");var type=StoryJson.Bounded(value.Type,24,true).ToLowerInvariant();if(!ActorTypes.Contains(type))throw new StoryException("invalid_transcript_actor");return new JsonObject{["type"]=type,["name"]=StoryJson.Bounded(value.Name,160,true),["id"]=value.Id is null?null:StoryJson.Bounded(value.Id,160),["avatar"]=value.Avatar is null?null:StoryJson.Bounded(value.Avatar,1000),["characterId"]=value.CharacterId is null?null:StoryJson.Bounded(value.CharacterId,160)};}
 static string RoleplayConfidence(string? value)=>value is null or ""?"estimated":value is "explicit" or "estimated" or "unknown"?value:throw new StoryException("invalid_roleplay_confidence");

 public async Task<object> StartSessionAsync(string campaign,string actor,TranscriptSessionWrite input,CancellationToken ct=default){
  var op=StoryJson.Id(input.OperationId).ToString();var name=StoryJson.Bounded(input.Name,120,true);var rp=StoryJson.Bounded(input.RoleplayTime,160,true);await campaigns.MembershipAsync(campaign,actor,true,ct);
  await store.Commands.WaitAsync(ct);LeafEntity session;try{await store.WritableAsync(ct);var slug=SessionSlug(campaign,op);var existing=await store.Entities.GetBySlugAsync("storyboard-campaign-session",slug,ct);if(existing is not null){await store.CheckProtectionAsync(existing,ct);if(existing.Data.Text("campaign")!=campaign||existing.Name!=name||existing.Data.Text("roleplay_anchor")!=rp)throw new StoryException("idempotency_conflict",409);session=existing;}else{var active=(await store.AllAsync("storyboard-campaign-session",new Dictionary<string,object?>{{"campaign",campaign},{"state","active"}},ct)).FirstOrDefault();if(active is not null)throw new StoryException("transcript_session_active",409);var now=clock.GetUtcNow();var data=await store.ProtectAsync(new JsonObject{["campaign"]=campaign,["state"]="active",["started_at"]=Iso(now),["started_by"]=actor,["roleplay_anchor"]=rp,["roleplay_anchor_at"]=Iso(now),["last_operation"]=op},ct);session=await store.ChangeAsync("storyboard-campaign-session",slug,name,_=>data,ct);}}finally{store.Commands.Release();}
  await AppendAsync(session,actor,op,new JsonObject{["kind"]="system",["channel"]="meta",["text"]="Session started",["actor"]=new JsonObject{{"type","system"},{"name","Storyboard"}},["roleplay_time"]=rp,["roleplay_confidence"]="explicit"},ct);return SessionProjection(session);
 }
 public async Task<object> EndSessionAsync(string campaign,string sessionId,string actor,TranscriptEndWrite input,CancellationToken ct=default){var op=StoryJson.Id(input.OperationId).ToString();var session=await RequireSessionAsync(campaign,sessionId,actor,true,ct);await store.Commands.WaitAsync(ct);try{await store.WritableAsync(ct);session=await store.ChangeAsync(session.TypeSlug,session.Slug,session.Name,old=>{var next=old!.Data.DeepClone().AsObject();if(next.Text("state")=="ended")return next;next["state"]="ended";next["ended_at"]=Iso(clock.GetUtcNow());next["last_operation"]=op;return next;},ct);}finally{store.Commands.Release();}await AppendAsync(session,actor,op,new JsonObject{["kind"]="system",["channel"]="meta",["text"]="Session ended",["actor"]=new JsonObject{{"type","system"},{"name","Storyboard"}}},ct);return SessionProjection(session);}
 public async Task<object> SetRoleplayTimeAsync(string campaign,string sessionId,string actor,TranscriptRoleplayTimeWrite input,CancellationToken ct=default){var op=StoryJson.Id(input.OperationId).ToString();var rp=StoryJson.Bounded(input.RoleplayTime,160,true);var session=await RequireSessionAsync(campaign,sessionId,actor,true,ct);if(session.Data.Text("state")!="active")throw new StoryException("transcript_session_ended",409);await store.Commands.WaitAsync(ct);try{await store.WritableAsync(ct);session=await store.ChangeAsync(session.TypeSlug,session.Slug,session.Name,old=>{var next=old!.Data.DeepClone().AsObject();next["roleplay_anchor"]=rp;next["roleplay_anchor_at"]=Iso(clock.GetUtcNow());next["last_operation"]=op;return next;},ct);}finally{store.Commands.Release();}await AppendAsync(session,actor,op,new JsonObject{["kind"]="roleplay-time",["channel"]="roleplay",["text"]="Roleplay time anchored",["actor"]=new JsonObject{{"type","system"},{"name","Game Master"}},["roleplay_time"]=rp,["roleplay_confidence"]="explicit"},ct);return SessionProjection(session);}
 public async Task<IReadOnlyList<object>> SessionsAsync(string campaign,string actor,CancellationToken ct=default){await campaigns.MembershipAsync(campaign,actor,false,ct);return (await store.AllAsync("storyboard-campaign-session",new Dictionary<string,object?>{{"campaign",campaign}},ct)).OrderByDescending(s=>s.Data.Text("started_at"),StringComparer.Ordinal).Select(SessionProjection).ToArray();}
 public async Task<object?> CurrentAsync(string campaign,string actor,CancellationToken ct=default){await campaigns.MembershipAsync(campaign,actor,false,ct);var session=(await store.AllAsync("storyboard-campaign-session",new Dictionary<string,object?>{{"campaign",campaign},{"state","active"}},ct)).OrderByDescending(s=>s.Data.Text("started_at"),StringComparer.Ordinal).FirstOrDefault();return session is null?null:SessionProjection(session);}

 async Task<bool> AppendAsync(LeafEntity session,string actor,string operation,JsonObject data,CancellationToken ct){data["event_id"]=operation;data["campaign"]=session.Data.Text("campaign");data["session"]=session.Id.ToString();data["recorded_by"]=actor;return await store.Records.AppendOnceAsync(Stream,operation,data,session.Id,actor,ct);}
 static (string Operation,string Text,string RoleplayTime,string Confidence,JsonObject Actor,JsonObject Data,string? Voice) EventData(TranscriptEventWrite input){var op=StoryJson.Id(input.OperationId).ToString();var kind=StoryJson.Bounded(input.Kind,32,true).ToLowerInvariant();if(!EventKinds.Contains(kind))throw new StoryException("invalid_transcript_event");var channel=StoryJson.Bounded(input.Channel,16,true).ToLowerInvariant();if(!Channels.Contains(channel))throw new StoryException("invalid_transcript_channel");var text=StoryJson.Bounded(input.Text,8000,true);var actor=Actor(input.Actor);var rp=input.RoleplayTime is null?"":StoryJson.Bounded(input.RoleplayTime,160);var confidence=RoleplayConfidence(input.RoleplayConfidence);string? voice=null;if(input.Speak){if(actor.Text("type")!="agent"||string.IsNullOrWhiteSpace(input.Voice))throw new StoryException("invalid_transcript_voice");voice=StoryJson.Bounded(input.Voice,256,true);}var data=new JsonObject{["kind"]=kind,["channel"]=channel,["text"]=text,["actor"]=actor,["roleplay_time"]=rp,["roleplay_confidence"]=confidence,["corrects"]=input.Corrects is null?null:StoryJson.Bounded(input.Corrects,80)};return(op,text,rp,confidence,actor,data,voice);}
 static void RequireSameEvent(LeafEntity session,LeafRecord existing,JsonObject data){if(existing.EntityId!=session.Id||existing.Data.Text("kind")!=data.Text("kind")||existing.Data.Text("channel")!=data.Text("channel")||existing.Data.Text("text")!=data.Text("text")||existing.Data.Text("roleplay_time")!=data.Text("roleplay_time")||existing.Data.Text("roleplay_confidence")!=data.Text("roleplay_confidence")||existing.Data.Text("corrects")!=data.Text("corrects")||!JsonNode.DeepEquals(existing.Data["actor"],data["actor"]))throw new StoryException("idempotency_conflict",409);}
 async Task<object> AppendEventAsync(LeafEntity session,string recordedBy,string jobAccount,TranscriptEventWrite input,CancellationToken ct){var value=EventData(input);var existing=(await store.Records.QueryAsync(Stream,new RecordQuery{ExternalId=value.Operation,Limit=1},ct)).SingleOrDefault();if(existing is not null)RequireSameEvent(session,existing,value.Data);var appended=existing is null&&await AppendAsync(session,recordedBy,value.Operation,value.Data,ct);if(input.Speak)await EnsureJobAsync(session,jobAccount,value.Operation,"tts",null,value.Text,value.Voice,input.Language,value.Actor,value.RoleplayTime,value.Confidence,ct);return new{accepted=true,idempotent=!appended,eventId=value.Operation};}
 public async Task<object> AddEventAsync(string campaign,string sessionId,string actor,TranscriptEventWrite input,CancellationToken ct=default){var session=await RequireSessionAsync(campaign,sessionId,actor,true,ct);return await AppendEventAsync(session,actor,actor,input,ct);}
 public async Task<object> AddAgentEventAsync(string campaign,string sessionId,string requester,TranscriptEventWrite input,CancellationToken ct=default){var session=await store.RequireAsync("storyboard-campaign-session",sessionId,ct);if(session.Data.Text("campaign")!=campaign)throw new StoryException("not_found",404);var value=EventData(input);if(value.Actor.Text("type") is not ("agent" or "system" or "npc"))throw new StoryException("invalid_transcript_actor");var campaignEntity=await store.RequireAsync("storyboard-campaign",campaign,ct);var account=campaignEntity.Data.Text("creator");if(account=="")throw new StoryException("campaign_creator_missing",409);var existing=(await store.Records.QueryAsync(Stream,new RecordQuery{ExternalId=value.Operation,Limit=1},ct)).SingleOrDefault();if(existing is not null)RequireSameEvent(session,existing,value.Data);var appended=existing is null&&await AppendAsync(session,requester,value.Operation,value.Data,ct);if(input.Speak)await EnsureJobAsync(session,account,value.Operation,"tts",null,value.Text,value.Voice,input.Language,value.Actor,value.RoleplayTime,value.Confidence,ct);return new{accepted=true,idempotent=!appended,eventId=value.Operation};}
 public async Task<object> AddAudioAsync(string campaign,string sessionId,string actor,TranscriptAudioWrite input,CancellationToken ct=default){var session=await RequireSessionAsync(campaign,sessionId,actor,true,ct);if(session.Data.Text("state")!="active")throw new StoryException("transcript_session_ended",409);var op=StoryJson.Id(input.OperationId).ToString();if(input.DurationMs is <250 or >120000)throw new StoryException("invalid_audio_duration");var mime=input.ContentType.Split(';')[0].Trim().ToLowerInvariant();var ext=mime switch{"audio/webm"=>"webm","audio/ogg"=>"ogg","audio/mp4"=>"m4a","audio/wav"=>"wav",_=>throw new StoryException("invalid_audio_type")};byte[] bytes;try{bytes=Convert.FromBase64String(input.AudioBase64);}catch(FormatException){throw new StoryException("invalid_audio");}if(bytes.Length is <32 or >6291456)throw new StoryException("invalid_audio_size");var digest=Convert.ToHexStringLower(SHA256.HashData(bytes));var actorData=Actor(input.Actor);var rp=input.RoleplayTime is null?"":StoryJson.Bounded(input.RoleplayTime,160);var existing=(await store.Records.QueryAsync(Stream,new RecordQuery{ExternalId=op,Limit=1},ct)).SingleOrDefault();if(existing is not null){if(existing.EntityId!=session.Id||existing.Data.Text("kind")!="audio"||existing.Data.Text("audio_sha256")!=digest||existing.Data.Text("content_type")!=mime||existing.Data.Number("duration_ms")!=input.DurationMs||existing.Data["actor"]?.ToJsonString()!=actorData.ToJsonString())throw new StoryException("idempotency_conflict",409);await EnsureJobAsync(session,actor,op,"stt",existing.Data.Text("audio_asset"),null,null,input.Language,actorData,rp,"estimated",ct);return new{accepted=true,idempotent=true,eventId=op};}await using var stream=new MemoryStream(bytes,false);var asset=await assets.UploadIdempotentAsync(stream,"storyboard-transcript-"+op,$"storyboard-{op}.{ext}",mime,ct);var data=new JsonObject{["kind"]="audio",["channel"]="irl",["text"]="Audio captured",["actor"]=actorData,["audio_asset"]=asset.AssetId,["audio_sha256"]=digest,["content_type"]=mime,["duration_ms"]=input.DurationMs,["captured_at"]=input.CapturedAt is null?null:StoryJson.Bounded(input.CapturedAt,80),["roleplay_time"]=rp,["roleplay_confidence"]="estimated",["derivation_state"]="pending"};var appended=await AppendAsync(session,actor,op,data,ct);await EnsureJobAsync(session,actor,op,"stt",asset.AssetId,null,null,input.Language,actorData,rp,"estimated",ct);return new{accepted=true,idempotent=!appended,eventId=op};}
 async Task EnsureJobAsync(LeafEntity session,string actor,string source,string kind,string? asset,string? text,string? voice,string? language,JsonObject actorData,string rp,string confidence,CancellationToken ct){var slug=JobSlug(session.Id.ToString(),source+":"+kind);var data=await store.ProtectAsync(new JsonObject{["campaign"]=session.Data.Text("campaign"),["session"]=session.Id.ToString(),["kind"]=kind,["state"]="pending",["source_event"]=source,["audio_asset"]=asset,["text"]=text,["voice"]=voice,["language"]=string.IsNullOrWhiteSpace(language)?"auto":StoryJson.Bounded(language,12),["actor"]=actorData.DeepClone(),["roleplay_time"]=rp,["roleplay_confidence"]=confidence,["attempts"]=0,["retry_at"]=0,["account"]=actor},ct);await store.ChangeAsync("storyboard-transcript-job",slug,$"{kind.ToUpperInvariant()} for transcript event",old=>{if(old is not null){if(old.Data.Text("session")!=session.Id.ToString()||old.Data.Text("source_event")!=source||old.Data.Text("kind")!=kind)throw new StoryException("idempotency_conflict",409);return old.Data.DeepClone().AsObject();}return data;},ct);}

 public async Task<object> PageAsync(string campaign,string sessionId,string actor,string? cursor,int? requestedLimit,CancellationToken ct=default){var session=await RequireSessionAsync(campaign,sessionId,actor,false,ct);var limit=Math.Clamp(requestedLimit??100,1,200);long? beforeId=null;DateTimeOffset? until=null;if(!string.IsNullOrWhiteSpace(cursor)){(beforeId,until)=await DecodeCursorAsync(session,cursor,ct);}var queryLimit=Math.Min(1000,limit+100);var rows=await store.Records.QueryAsync(Stream,new RecordQuery{EntityId=session.Id,Until=until?.AddTicks(1),Limit=queryLimit},ct);if(beforeId is not null)rows=rows.Where(r=>r.CreatedAt<until||r.CreatedAt==until&&r.Id<beforeId).ToArray();var page=rows.Take(limit).ToArray();var events=page.Select(r=>Project(session,r,campaign)).ToArray();var next=rows.Count>limit&&page.Length>0?await EncodeCursorAsync(session,page[^1],ct):null;return new{session=SessionProjection(session),events,nextCursor=next,hasEarlier=next is not null};}
 object Project(LeafEntity session,LeafRecord record,string campaign){var d=record.Data;var rp=d.Text("roleplay_time");var confidence=d.Text("roleplay_confidence");if(rp==""){var anchor=session.Data.Text("roleplay_anchor","Unknown roleplay time");if(DateTimeOffset.TryParse(session.Data.Text("roleplay_anchor_at"),out var at)){var delta=record.CreatedAt-at;var sign=delta<TimeSpan.Zero?"-":"+";delta=delta.Duration();rp=$"{anchor} · ~{sign}{(int)delta.TotalHours:00}:{delta.Minutes:00}";confidence="estimated";}else{rp=anchor;confidence="unknown";}}var id=d.Text("event_id",record.Id.ToString());return new{id,sequence=record.Id,irlAt=Iso(record.CreatedAt),roleplayTime=rp,roleplayConfidence=confidence==""?"unknown":confidence,kind=d.Text("kind"),channel=d.Text("channel"),text=d.Text("text"),actor=d["actor"]?.DeepClone(),corrects=d.Text("corrects")==""?null:d.Text("corrects"),sourceEvent=d.Text("source_event")==""?null:d.Text("source_event"),durationMs=d.Number("duration_ms"),derivationState=d.Text("derivation_state")==""?null:d.Text("derivation_state"),audioUrl=d.Text("audio_asset")==""?null:$"/api/campaigns/{campaign}/transcript/audio/{Uri.EscapeDataString(id)}"};}
 async Task<string> EncodeCursorAsync(LeafEntity session,LeafRecord record,CancellationToken ct){var value=$"1|{session.Id:D}|{record.Id}|{record.CreatedAt.UtcTicks}";var config=(await store.ConfigAsync(ct))!;var sig=Convert.ToHexStringLower(HMACSHA256.HashData(Encoding.UTF8.GetBytes(config.Data.Text("proxy_secret")),Encoding.UTF8.GetBytes(value)));return Convert.ToBase64String(Encoding.UTF8.GetBytes(value+"|"+sig)).TrimEnd('=').Replace('+','-').Replace('/','_');}
 async Task<(long,DateTimeOffset)> DecodeCursorAsync(LeafEntity session,string cursor,CancellationToken ct){try{var encoded=cursor.Replace('-','+').Replace('_','/');encoded=encoded.PadRight((encoded.Length+3)/4*4,'=');var parts=Encoding.UTF8.GetString(Convert.FromBase64String(encoded)).Split('|');if(parts.Length!=5||parts[0]!="1"||parts[1]!=session.Id.ToString("D")||!long.TryParse(parts[2],out var id)||!long.TryParse(parts[3],out var ticks))throw new FormatException();var value=string.Join('|',parts[..4]);var config=(await store.ConfigAsync(ct))!;var expected=Convert.ToHexStringLower(HMACSHA256.HashData(Encoding.UTF8.GetBytes(config.Data.Text("proxy_secret")),Encoding.UTF8.GetBytes(value)));if(!StoryJson.Equal(expected,parts[4]))throw new FormatException();return(id,new DateTimeOffset(ticks,TimeSpan.Zero));}catch(Exception e)when(e is FormatException or ArgumentException){throw new StoryException("invalid_transcript_cursor");}}
 public async Task<(byte[] Bytes,string ContentType)?> AudioAsync(string campaign,string actor,string eventId,CancellationToken ct=default){await campaigns.MembershipAsync(campaign,actor,false,ct);var matches=await store.Records.QueryAsync(Stream,new RecordQuery{ExternalId=eventId,Limit=1},ct);var record=matches.SingleOrDefault();if(record is null||record.Data.Text("campaign")!=campaign||record.Data.Text("audio_asset")=="")throw new StoryException("not_found",404);var file=await assets.ReadAsync(record.Data.Text("audio_asset"),ct);return file is null?null:(file.Bytes,file.ContentType);}

 protected override async Task ExecuteAsync(CancellationToken stoppingToken){while(!stoppingToken.IsCancellationRequested){try{var now=clock.GetUtcNow().ToUnixTimeSeconds();var jobs=(await store.AllAsync("storyboard-transcript-job",ct:stoppingToken)).Where(j=>j.Data.Text("state") is "pending" or "waiting"&&j.Data.Number("retry_at")<=now).OrderBy(j=>j.CreatedAt).Take(3).ToArray();foreach(var job in jobs)await ProcessAsync(job,stoppingToken);}catch(OperationCanceledException)when(stoppingToken.IsCancellationRequested){break;}catch(Exception e){logger.LogError(e,"Storyboard transcript worker pass failed");}await Task.Delay(TimeSpan.FromSeconds(5),stoppingToken);}}
 async Task ProcessAsync(LeafEntity job,CancellationToken ct){try{await SetJobAsync(job,"processing",null,null,ct);job=await store.RequireAsync(job.TypeSlug,job.Id.ToString(),ct);if(job.Data.Text("kind")=="stt")await TranscribeAsync(job,ct);else await SpeakAsync(job,ct);}catch(OperationCanceledException){throw;}catch(Exception e){var attempts=job.Data.Number("attempts")+1;var delay=Math.Min(300,5*Math.Pow(2,Math.Min(attempts,6)));await SetJobAsync(job,"waiting",e.Message,clock.GetUtcNow().AddSeconds(delay).ToUnixTimeSeconds(),ct);logger.LogWarning(e,"Storyboard transcript derivation {Job} delayed",job.Id);}}
 async Task TranscribeAsync(LeafEntity job,CancellationToken ct){var status=await compute.GetStatusAsync(ct);if(status?.Capabilities.FirstOrDefault(c=>c.Slug=="stt")?.Status?.Equals("Running",StringComparison.OrdinalIgnoreCase)!=true)throw new ComputeJobException("Speech-to-text is not running; source audio is preserved");var file=await assets.ReadAsync(job.Data.Text("audio_asset"),ct)??throw new StoryException("transcript_audio_missing",409);var payload=new JsonObject{["audio_base64"]=Convert.ToBase64String(file.Bytes),["language"]=job.Data.Text("language","auto"),["task"]="transcribe",["word_timestamps"]=true,["vad_filter"]=true};var result=await compute.SubmitAsync("stt",payload,new ComputeJobOptions{Async=false,IdempotencyKey="storyboard-stt-"+job.Data.Text("source_event"),JobName="Storyboard session transcription",Rationale="Derive searchable campaign speech while preserving the source audio"},ct);var body=result.InlineResult;var text=body?.Text("text");if(string.IsNullOrWhiteSpace(text))throw new StoryException("transcript_empty",409);var session=await store.RequireAsync("storyboard-campaign-session",job.Data.Text("session"),ct);await AppendAsync(session,job.Data.Text("account"),"stt-"+job.Data.Text("source_event"),new JsonObject{["kind"]="speech",["channel"]="roleplay",["text"]=StoryJson.Bounded(text,8000,true),["actor"]=job.Data["actor"]?.DeepClone(),["source_event"]=job.Data.Text("source_event"),["roleplay_time"]=job.Data.Text("roleplay_time"),["roleplay_confidence"]=job.Data.Text("roleplay_confidence"),["compute_job"]=result.JobId,["language"]=body?.Text("language")},ct);await SetJobAsync(job,"completed",null,null,ct);}
 async Task SpeakAsync(LeafEntity job,CancellationToken ct){var payload=new JsonObject{["text"]=job.Data.Text("text"),["voice"]=job.Data.Text("voice")};if(job.Data.Text("language") is not "" and not "auto")payload["language"]=job.Data.Text("language");var result=await compute.SubmitAsync("tts",payload,new ComputeJobOptions{Async=false,IdempotencyKey="storyboard-tts-"+job.Data.Text("source_event"),JobName="Storyboard agent voice",Rationale="Speak an explicitly logged campaign agent utterance"},ct);if(string.IsNullOrWhiteSpace(result.JobId))throw new StoryException("transcript_tts_output_missing",409);using var output=await compute.DownloadOutputAsync("tts",result.JobId,ct:ct)??throw new StoryException("transcript_tts_output_missing",409);var asset=await assets.UploadIdempotentAsync(output.Content,"storyboard-tts-"+job.Data.Text("source_event"),$"storyboard-{job.Data.Text("source_event")}.mp3",output.ContentType??"audio/mpeg",ct);var session=await store.RequireAsync("storyboard-campaign-session",job.Data.Text("session"),ct);await AppendAsync(session,job.Data.Text("account"),"tts-"+job.Data.Text("source_event"),new JsonObject{["kind"]="tts",["channel"]="meta",["text"]="Generated voice",["actor"]=job.Data["actor"]?.DeepClone(),["source_event"]=job.Data.Text("source_event"),["audio_asset"]=asset.AssetId,["roleplay_time"]=job.Data.Text("roleplay_time"),["roleplay_confidence"]=job.Data.Text("roleplay_confidence"),["compute_job"]=result.JobId},ct);await SetJobAsync(job,"completed",null,null,ct);}
 async Task SetJobAsync(LeafEntity job,string state,string? error,long? retry,CancellationToken ct){await store.ChangeAsync(job.TypeSlug,job.Slug,job.Name,old=>{var next=old!.Data.DeepClone().AsObject();next["state"]=state;next["error"]=error;if(retry.HasValue)next["retry_at"]=retry.Value;if(state=="processing")next["attempts"]=next.Number("attempts")+1;return next;},ct);}
}
